# -*- coding: utf-8 -*-
##
#    Copyright (c) 2015 Cyrus Daboo. All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
##


from pycalendar.datetime import DateTime
from pycalendar.icalendar.calendar import Calendar
from pycalendar.icalendar.patch import Command, Path, PatchDocument
import operator
import unittest
import itertools
import json
import os

data = {
    "create_component_simple": [
        {
            "title": "Add one component to a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Add two components to a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Add one component to an event",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Event reminder
TRIGGER:-PT8M
UID:D9D1AC84-F629-4B9D-9B6B-4A6CA9A11FEF
END:VALARM
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR/VEVENT
BEGIN:VALARM
UID:D9D1AC84-F629-4B9D-9B6B-4A6CA9A11FEF
DESCRIPTION:Event reminder
TRIGGER:-PT8M
ACTION:DISPLAY
END:VALARM
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
    ],

    "create_property_simple": [
        {
            "title": "Add one property to a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR#
CALSCALE:GREGORIAN
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Add two properties to a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
REFRESH-INTERVAL:10
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR#
CALSCALE:GREGORIAN
REFRESH-INTERVAL:10
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Add one property to an event",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
STATUS:CANCELLED
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR/VEVENT#
STATUS:CANCELLED
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Add two properties to an event",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
STATUS:CANCELLED
SUMMARY:New Year's Day
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:CREATE
TARGET:/VCALENDAR/VEVENT#
STATUS:CANCELLED
TRANSP:TRANSPARENT
END:CREATE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "update_component_simple": [
        {
            "title": "Update one component in a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Update one, add another component to a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20030101
DTSTART;VALUE=DATE:20030101
DTEND;VALUE=DATE:20030102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:New Year's Day - cancelled
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20030101
DTSTART;VALUE=DATE:20030101
DTEND;VALUE=DATE:20030102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:New Year's Day - cancelled
END:VEVENT
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Update one component in a calendar with others present",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20030101
DTSTART;VALUE=DATE:20030101
DTEND;VALUE=DATE:20030102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:New Year's Day - cancelled
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - party time
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20030101
DTSTART;VALUE=DATE:20030101
DTEND;VALUE=DATE:20030102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - it is on again!
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=20030101]
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20030101
DTSTART;VALUE=DATE:20030101
DTEND;VALUE=DATE:20030102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day - it is on again!
END:VEVENT
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "update_component_recur": [
        {
            "title": "Update one property in an instance",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20020102
DTSTART;VALUE=DATE:20020102
DTEND;VALUE=DATE:20020103
DTSTAMP:20020101T000000Z
SUMMARY:New Year's Day - party time
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=20020102]#SUMMARY
SUMMARY:New Year's Day - party time
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "update_property_simple": [
        {
            "title": "Update (add) one property in a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT#TRANSP
TRANSP:TRANSPARENT
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Update (existing) property in a calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT#TRANSP
TRANSP:TRANSPARENT
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Update one property in all events",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CONFIRMED
SUMMARY:April Fool's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CONFIRMED
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT#STATUS
STATUS:CONFIRMED
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Update one property in one event",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CANCELLED
SUMMARY:April Fool's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
STATUS:CONFIRMED
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:UPDATE
TARGET:/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252]#STATUS
STATUS:CONFIRMED
END:UPDATE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "delete_component_simple": [
        {
            "title": "Remove one component from single event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one component from multi event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252]
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove all components from multi event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one alarm from single event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
BEGIN:VALARM
UID:D9D1AC84-F629-4B9D-9B6B-4A6CA9A11FEF
DESCRIPTION:Event reminder
TRIGGER:-PT8M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT/VALARM
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one alarm from single multi alarm event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
BEGIN:VALARM
UID:D9D1AC84-F629-4B9D-9B6B-4A6CA9A11FEF
DESCRIPTION:Event reminder
TRIGGER:-PT8M
ACTION:DISPLAY
END:VALARM
BEGIN:VALARM
UID:D78F6991-DFDD-491B-8334-FA9BF8E4F11C
DESCRIPTION:Event reminder
TRIGGER:-PT8M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Event reminder
TRIGGER:-PT8M
UID:D9D1AC84-F629-4B9D-9B6B-4A6CA9A11FEF
END:VALARM
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT/VALARM[UID=D78F6991-DFDD-491B-8334-FA9BF8E4F11C]
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "delete_property_simple": [
        {
            "title": "Remove one property from VCALENDAR",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR#CALSCALE
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one property from VEVENT",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT#RRULE
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one property from multi event calendar",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:DFAEA248-AC4E-44D6-8FA3-ACAAA7BA7943
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:DFAEA248-AC4E-44D6-8FA3-ACAAA7BA7943
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252]#RRULE
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one of many properties from VEVENT",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT#ATTENDEE[=mailto:user03@example.com]
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one of many properties from one of many VEVENTs",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20120101
DTSTART;VALUE=DATE:20120101
DTEND;VALUE=DATE:20120102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20120101
DTSTART;VALUE=DATE:20120101
DTEND;VALUE=DATE:20120102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT[RECURRENCE-ID=20120101]#ATTENDEE[=mailto:user03@example.com]
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
    "delete_parameter_simple": [
        {
            "title": "Remove parameter from all properties in VEVENT",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE:mailto:user01@example.com
ATTENDEE:mailto:user02@example.com
ATTENDEE:mailto:user03@example.com
ATTENDEE:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT#ATTENDEE;PARTSTAT
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove parameter from one property in VEVENT",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT#ATTENDEE[=mailto:user03@example.com];PARTSTAT
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
        {
            "title": "Remove one parameter from one of many parameters from one of many VEVENTs",
            "before": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20120101
DTSTART;VALUE=DATE:20120101
DTEND;VALUE=DATE:20120102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "after": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID;VALUE=DATE:20120101
DTSTART;VALUE=DATE:20120101
DTEND;VALUE=DATE:20120102
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user01@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user02@example.com
ATTENDEE:mailto:user03@example.com
ATTENDEE;PARTSTAT=NEEDS-ACTION:mailto:user04@example.com
DTSTAMP:20020101T000000Z
ORGANIZER:mailto:user01@example.com
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
""",
            "patch": """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VPATCH
BEGIN:DELETE
TARGET:/VCALENDAR/VEVENT[RECURRENCE-ID=20120101]#ATTENDEE[=mailto:user03@example.com];PARTSTAT
END:DELETE
END:VPATCH
END:VCALENDAR
""",
        },
    ],
}


class TestPatchDocument(unittest.TestCase):

    def _testPatch(self, data):

        for ctr, items in enumerate(data):
            calendar = Calendar.parseText(items["before"])
            patcher = PatchDocument(Calendar.parseText(items["patch"]))
            patcher.applyPatch(calendar)
            self.assertEqual(str(calendar), items["after"].replace("\n", "\r\n"), msg="Failed test #{}: {}\n{}".format(ctr + 1, items["title"], str(calendar)))

    def test_createComponent_Simple(self):
        """
        Test that creation of a single component works.
        """

        self._testPatch(data["create_component_simple"])

    def test_createProperty_Simple(self):
        """
        Test that creation of a single property works.
        """

        self._testPatch(data["create_property_simple"])

    def test_updateComponent_Simple(self):
        """
        Test that update of components works.
        """

        self._testPatch(data["update_component_simple"])

    def test_updateComponent_Recur(self):
        """
        Test that update of components works.
        """

        self._testPatch(data["update_component_recur"])

    def test_updateProperty_Simple(self):
        """
        Test that update of a single property works.
        """

        self._testPatch(data["update_property_simple"])

    def test_deleteComponent_Simple(self):
        """
        Test that deletion of a single component works.
        """

        self._testPatch(data["delete_component_simple"])

    def test_deleteProperty_Simple(self):
        """
        Test that deletion of a single property works.
        """

        self._testPatch(data["delete_property_simple"])

    def test_deleteParameter_Simple(self):
        """
        Test that deletion of a single parameter works.
        """

        self._testPatch(data["delete_parameter_simple"])


def componentData(data):
    """
    Parse the data item into a component.

    @return: a component
    @rtype: L{Component}
    """

    # Data must be a set of components. Wrap the data inside a VCALENDAR and parse
    newdata = """BEGIN:VCALENDAR
VERSION:2.0
PRODID:ignore
{}
END:VCALENDAR
""".format(data)
    calendar = Calendar.parseText(newdata)
    return calendar.getComponents()[0]


class TestCommand(unittest.TestCase):

    def testCreate(self):
        test_data = (
            # Valid
            (Command.CREATE, "/VCALENDAR", componentData("BEGIN:VEVENT\r\nEND:VEVENT\r\n"), True,),
            (Command.CREATE, Path("/VCALENDAR"), componentData("BEGIN:VEVENT\r\nEND:VEVENT\r\n"), True,),
            (Command.UPDATE, "/VCALENDAR#VERSION", componentData("BEGIN:UPDATE\r\nVERSION:2.0\r\nEND:UPDATE\r\n"), True,),
            (Command.UPDATE, Path("/VCALENDAR#VERSION"), componentData("BEGIN:UPDATE\r\nVERSION:2.0\r\nEND:UPDATE\r\n"), True,),
            (Command.DELETE, "/VCALENDAR#VERSION", None, True,),

            # Invalid
            ("foo", "/VCALENDAR", componentData("BEGIN:VEVENT\r\nEND:VEVENT\r\n"), False,),
            (Command.CREATE, 1, componentData("BEGIN:VEVENT\r\nEND:VEVENT\r\n"), False,),
            (Command.CREATE, "/VCALENDAR", 1, False,),
            (Command.CREATE, "/VCALENDAR", None, False,),
            (Command.UPDATE, "/VCALENDAR#VERSION", None, False,),
            (Command.DELETE, "/VCALENDAR#VERSION", componentData("BEGIN:UPDATE\r\nVERSION:2.0\r\nEND:UPDATE\r\n"), False,),
        )

        for action, path, data, valid in test_data:
            try:
                command = Command.create(action, path, data)
            except ValueError:
                self.assertFalse(valid)
            else:
                self.assertTrue(valid)
                self.assertTrue(isinstance(command, Command))


class TestPath(unittest.TestCase):

    test_data = (
        # Valid

        # Components
        (
            "/VCALENDAR",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
            ],
            None,
            None,
        ),
        (
            "/VCALENDAR/VEVENT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            None,
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234]"),
            ],
            None,
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234%2F4567]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234/4567]"),
            ],
            None,
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]"),
            ],
            None,
            None,
        ),

        # Properties
        (
            "/VCALENDAR#VERSION",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
            ],
            Path.PropertySegment("VERSION"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT#SUMMARY",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("SUMMARY"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT#SUMMARY[=abc]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("SUMMARY[=abc]"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT#SUMMARY[=a%2Fc]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("SUMMARY[=a/c]"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT#SUMMARY[!abc]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("SUMMARY[!abc]"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234]#SUMMARY",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234]"),
            ],
            Path.PropertySegment("SUMMARY"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234]#SUMMARY[=abc]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234]"),
            ],
            Path.PropertySegment("SUMMARY[=abc]"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]#SUMMARY",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]"),
            ],
            Path.PropertySegment("SUMMARY"),
            None,
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]#SUMMARY[=abc]",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]"),
            ],
            Path.PropertySegment("SUMMARY[=abc]"),
            None,
        ),

        # Parameters
        (
            "/VCALENDAR#VERSION;VALUE",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
            ],
            Path.PropertySegment("VERSION"),
            Path.ParameterSegment("VALUE"),
        ),
        (
            "/VCALENDAR/VEVENT#ATTENDEE;PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("ATTENDEE"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT#ATTENDEE[=abc];PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("ATTENDEE[=abc]"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT#ATTENDEE[=a%2Fc];PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("ATTENDEE[=a/c]"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT#ATTENDEE[!abc];PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT"),
            ],
            Path.PropertySegment("ATTENDEE[!abc]"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234]#ATTENDEE;PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234]"),
            ],
            Path.PropertySegment("ATTENDEE"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234]#ATTENDEE[=abc];PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234]"),
            ],
            Path.PropertySegment("ATTENDEE[=abc]"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]#ATTENDEE;PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]"),
            ],
            Path.PropertySegment("ATTENDEE"),
            Path.ParameterSegment("PARTSTAT"),
        ),
        (
            "/VCALENDAR/VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]#ATTENDEE[=abc];PARTSTAT",
            True,
            [
                Path.ComponentSegment("VCALENDAR"),
                Path.ComponentSegment("VEVENT[UID=1234][RECURRENCE-ID=20150907T120000Z]"),
            ],
            Path.PropertySegment("ATTENDEE[=abc]"),
            Path.ParameterSegment("PARTSTAT"),
        ),

        # Invalid
    )

    def testParse(self):

        for strpath, valid, components, property, parameter in TestPath.test_data:
            try:
                path = Path(strpath)
            except ValueError:
                self.assertFalse(valid)
            else:
                self.assertTrue(valid)
                self.assertEqual(path.components, components)
                self.assertEqual(path.property, property)
                self.assertEqual(path.parameter, parameter)

    def testType(self):

        data = [
            ("/VCALENDAR", True, False, False, False, False,),
            ("/VCALENDAR/VEVENT", True, False, False, False, False,),
            ("/VCALENDAR/VEVENT#SUMMARY", False, True, False, False, False,),
            ("/VCALENDAR/VEVENT#", False, False, True, False, False,),
            ("/VCALENDAR/VEVENT#SUMMARY;X-PARAM", False, False, False, True, False,),
            ("/VCALENDAR/VEVENT#SUMMARY;", False, False, False, False, True,),
        ]

        for strpath, isComponent, isProperty, isPropertyNoName, isParameter, isParameterNoName in data:
            path = Path(strpath)
            self.assertEqual(path.targetComponent(), isComponent)
            self.assertEqual(path.targetProperty(), isProperty)
            self.assertEqual(path.targetPropertyNoName(), isPropertyNoName)
            self.assertEqual(path.targetParameter(), isParameter)
            self.assertEqual(path.targetParameterNoName(), isParameterNoName)

    def testMatch_Components_Simple(self):

        icalendar = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
"""

        calendar = Calendar.parseText(icalendar.replace("\n", "\r\n"))
        path = Path("/VCALENDAR")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar)

        path = Path("/VCALENDAR/VEVENT")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar.getComponents("VEVENT")[0])

        path = Path("/VCALENDAR/VEVENT[UID=123]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar.getComponents("VEVENT")[0])

        path = Path("/VCALENDAR/VEVENT[UID=123][RECURRENCE-ID=20150101T000000Z]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar.getComponents("VEVENT")[0])

        path = Path("/VCALENDAR/VEVENT[UID=123][RECURRENCE-ID=]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=20020101]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar.getComponents("VEVENT")[0])

    def testMatch_Components_Multiple(self):

        icalendar = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:New Year's Day
END:VEVENT
BEGIN:VEVENT
UID:165EF135-BA92-435A-88C9-562F95030908
DTSTART;VALUE=DATE:20020401
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:April Fool's Day
END:VEVENT
BEGIN:VEVENT
UID:5EA5AF47-77F5-4EEE-9944-69651C97755B
DTSTART;VALUE=DATE:20020921
DURATION:P1D
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY
SUMMARY:Birthday
END:VEVENT
END:VCALENDAR
"""

        calendar = Calendar.parseText(icalendar.replace("\n", "\r\n"))
        components_by_uid = dict([(component.getUID(), component) for component in calendar.getComponents()])

        path = Path("/VCALENDAR")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar)

        path = Path("/VCALENDAR/VEVENT")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 3)
        self.assertEqual(
            set([item.getUID() for item in matched]),
            set(components_by_uid.keys()),
        )

        path = Path("/VCALENDAR/VEVENT[UID=123]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        for key in components_by_uid.keys():
            path = Path("/VCALENDAR/VEVENT[UID={key}]".format(key=key))
            matched = path.match(calendar)
            self.assertEqual(len(matched), 1)
            self.assertIs(matched[0], components_by_uid[key])

        path = Path("/VCALENDAR/VEVENT[UID=123][RECURRENCE-ID=20150101T000000Z]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            components_by_uid["C3184A66-1ED0-11D9-A5E0-000A958A3252"],
        )

        for key in components_by_uid.keys():
            path = Path("/VCALENDAR/VEVENT[UID={key}][RECURRENCE-ID=20150101T000000Z]".format(key=key))
            matched = path.match(calendar)
            self.assertEqual(len(matched), 1)

        for key in components_by_uid.keys():
            path = Path("/VCALENDAR/VEVENT[UID={key}][RECURRENCE-ID=]".format(key=key))
            matched = path.match(calendar)
            self.assertEqual(len(matched), 1)
            self.assertIs(matched[0], components_by_uid[key])

    def testMatch_Components_Recurring(self):

        icalendar = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART:20020101T120000Z
DURATION:PT1H
DTSTAMP:20020101T000000Z
RRULE:FREQ=DAILY
SUMMARY:Meeting
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID:20020102T120000Z
DTSTART:20020102T130000Z
DURATION:PT1H
DTSTAMP:20020101T000000Z
SUMMARY:Meeting #2
END:VEVENT
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
RECURRENCE-ID:20020103T120000Z
DTSTART:20020103T140000Z
DURATION:PT1H
DTSTAMP:20020101T000000Z
SUMMARY:Meeting #3
END:VEVENT
END:VCALENDAR
"""

        calendar = Calendar.parseText(icalendar.replace("\n", "\r\n"))
        components_by_rid = dict([(component.getRecurrenceID(), component) for component in calendar.getComponents()])

        path = Path("/VCALENDAR")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], calendar)

        path = Path("/VCALENDAR/VEVENT")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 3)
        self.assertEqual(
            set([item.getRecurrenceID() for item in matched]),
            set(components_by_rid.keys()),
        )

        path = Path("/VCALENDAR/VEVENT[UID=123][RECURRENCE-ID=20150101T000000Z]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        for key in components_by_rid.keys():
            path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID={key}]".format(key=key if key else ""))
            matched = path.match(calendar)
            self.assertEqual(len(matched), 1)
            self.assertIs(matched[0], components_by_rid[key])

        path = Path("/VCALENDAR/VEVENT[UID=C3184A66-1ED0-11D9-A5E0-000A958A3252][RECURRENCE-ID=]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertIs(matched[0], components_by_rid[None])

    def testMatch_Properties_Simple(self):

        icalendar = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
"""

        calendar = Calendar.parseText(icalendar.replace("\n", "\r\n"))
        path = Path("/VCALENDAR#VERSION")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar, calendar.getProperties("VERSION")[0],),
        )

        path = Path("/VCALENDAR#")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar, None,),
        )

        path = Path("/VCALENDAR#FOOBAR")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#SUMMARY")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("SUMMARY")[0],),
        )

        path = Path("/VCALENDAR/VEVENT#")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], None,),
        )

        # Non-existent - for_update changes behavior
        path = Path("/VCALENDAR/VEVENT#FOOBAR")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#FOOBAR")
        matched = path.match(calendar, for_update=True)
        self.assertEqual(len(matched), 1)

        path = Path("/VCALENDAR/VEVENT#SUMMARY[=New Year's Day]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("SUMMARY")[0],),
        )

        # Non-existent - for_update does not change behavior
        path = Path("/VCALENDAR/VEVENT#SUMMARY[=New Years Day]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#SUMMARY[=New Years Day]")
        matched = path.match(calendar, for_update=True)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#DTSTART[=20020101]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("DTSTART")[0],),
        )

        path = Path("/VCALENDAR/VEVENT#RRULE[=20020101]")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

    def testMatch_Parameters_Simple(self):

        icalendar = """BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//example.com//Example v0.1//EN
BEGIN:VEVENT
UID:C3184A66-1ED0-11D9-A5E0-000A958A3252
DTSTART;VALUE=DATE:20020101
DTEND;VALUE=DATE:20020102
DTSTAMP:20020101T000000Z
RRULE:FREQ=YEARLY;UNTIL=20031231;BYMONTH=1
SUMMARY:New Year's Day
END:VEVENT
END:VCALENDAR
"""

        calendar = Calendar.parseText(icalendar.replace("\n", "\r\n"))

        path = Path("/VCALENDAR/VEVENT#SUMMARY;X-PARAM")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("SUMMARY")[0], "X-PARAM",)
        )

        path = Path("/VCALENDAR/VEVENT#SUMMARY;")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("SUMMARY")[0], None,)
        )

        path = Path("/VCALENDAR/VEVENT#FOOBAR;X-PARAM")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#SUMMARY[=New Year's Day];X-PARAM")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("SUMMARY")[0], "X-PARAM",)
        )

        path = Path("/VCALENDAR/VEVENT#SUMMARY[=New Years Day];X-PARAM")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 0)

        path = Path("/VCALENDAR/VEVENT#DTSTART[=20020101];VALUE")
        matched = path.match(calendar)
        self.assertEqual(len(matched), 1)
        self.assertEqual(
            matched[0],
            (calendar.getComponents()[0], calendar.getComponents()[0].getProperties("DTSTART")[0], "VALUE",)
        )


class TestComponentSegment(unittest.TestCase):

    test_data = (
        # Valid
        ("VCALENDAR", True, "VCALENDAR", None, None, None,),
        ("VCALENDAR[UID=1234]", True, "VCALENDAR", "1234", None, None,),
        ("VCALENDAR[UID=1234%2F4567]", True, "VCALENDAR", "1234/4567", None, None,),
        ("VCALENDAR[UID=1234][RECURRENCE-ID=]", True, "VCALENDAR", "1234", True, None,),
        ("VCALENDAR[UID=1234][RECURRENCE-ID=20150907T120000Z]", True, "VCALENDAR", "1234", True, "20150907T120000Z",),

        # Invalid
        ("VCALENDAR[]", False, None, None, None, None,),
        ("VCALENDAR[foo]", False, None, None, None, None,),
        ("VCALENDAR[foo=bar]", False, None, None, None, None,),
        ("VCALENDAR[UID=", False, None, None, None, None,),
        ("VCALENDAR[UID=1234][]", False, None, None, None, None,),
        ("VCALENDAR[UID=1234][foo=bar]", False, None, None, None, None,),
        ("VCALENDAR[UID=1234][RECURRENCE-ID=", False, None, None, None, None,),
    )

    def testParse(self):

        for segment, valid, name, uid, rid, rid_value in TestComponentSegment.test_data:
            try:
                component = Path.ComponentSegment(segment)
            except ValueError:
                self.assertFalse(valid)
            else:
                self.assertTrue(valid)
                self.assertEqual(component.name, name)
                self.assertEqual(component.uid, uid)
                self.assertEqual(component.rid, rid)
                self.assertEqual(component.rid_value, DateTime.parseText(rid_value) if rid_value else None)


class TestPropertySegment(unittest.TestCase):

    test_data = (
        # Valid
        ("STATUS", True, "STATUS", None,),
        ("STATUS[=COMPLETED]", True, "STATUS", ("COMPLETED", operator.eq,),),
        ("STATUS[!COMPLETED]", True, "STATUS", ("COMPLETED", operator.ne,),),
        ("SUMMARY[=a%2Fb]", True, "SUMMARY", ("a/b", operator.eq,),),
        ("", True, "", None,),

        # Invalid
        ("STATUS[]", False, None, None,),
        ("STATUS[foo]", False, None, None,),
        ("STATUS[=]", False, None, None,),
        ("STATUS[=COMPLETED", False, None, None,),
        ("STATUS[=COMPLETED][=FAILED]", False, None, None,),
    )

    def testParse(self):

        for segment, valid, name, matchCondition in TestPropertySegment.test_data:
            try:
                property = Path.PropertySegment(segment)
            except ValueError:
                self.assertFalse(valid)
            else:
                self.assertTrue(valid)
                self.assertEqual(property.name, name)
                self.assertEqual(property.matchCondition, matchCondition)


class TestParameterSegment(unittest.TestCase):

    test_data = (
        # Valid
        ("PARTSTAT", True, "PARTSTAT",),
        ("", True, "",),

        # Invalid
        ("PARTSTAT[]", False, None,),
        ("PARTSTAT[", False, None,),
        ("PARTSTAT[=NEEDS-ACTION]", False, None,),
    )

    def testParse(self):

        for segment, valid, name in TestParameterSegment.test_data:
            try:
                property = Path.ParameterSegment(segment)
            except ValueError:
                self.assertFalse(valid)
            else:
                self.assertTrue(valid)
                self.assertEqual(property.name, name)

if __name__ == '__main__':
    all_data = list(itertools.chain(*data.values()))
    with open(os.path.join(os.path.dirname(__file__), "patch_examples.json"), "w") as f:
        f.write(json.dumps(all_data, indent=2))
    print("Updated patch_example.json")
